version: '3.9'

services:
  web:
    build: .
    image: game-auction-server:latest
    container_name: game-auction-server-container
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR=value
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - my_network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: auctionServer
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true

# Version : 버전 명시. Docker Engine 또는 docker-compose 의 버전에 맞는 권장사항 파일 버전
# Service : Docker compose에서 실행할 컨테이너를 정의한다. 이미지,컨테이너 이름, 사용할 포트번호, 환경변수 등
# Networks : 각 서비스 간의 네트워크 연결을 정의한다. 이름과 드라이버 등의 정보를 포함한다. [Ex) mysql driver,password,userid..]
# Volumes :  어플리케이션에서 사용하는 데이터 볼륨을 정의한다. 이름, 드라이버, 옵션 등
# Environments : 서비스에서 사용할 환경변수를 정의한다.
# Configuration : 서비스에서 사용할 환경 설정 파일을 정의한다.
#출처 링크 : https://data-newbie.tistory.com/930
